configure.ac: add lib math for composite enabled builds
The composite enabled builds require lib math to be
present on the linker command line otherwise we get
ld: composite-engine.o: undefined reference to symbol 'exp@@GLIBC_2.2.5'
during compilation.

Signed-off-by: Awais Belal <awais_belal@mentor.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>